apiVersion: v1
data:
   config.py.template: {{ (.Files.Get "conf/config.py.template") . | quote}}
kind: ConfigMap
metadata:
  name: {{ include "pyapi.fullname" . }}-config
{{/*data:*/}}
{{/*{{ (.Files.Glob "files/*").AsConfig | indent 2 }}*/}}